### ISSUE TITLE
Discussons and enhancemens to the Galaxy notification framework

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-au/elixir-biocommons-colab#5]
* create a Admin UI to send unifications
* UX roundup and fixes

**Comment by bgruening** [comment]
@itisAliRH @electronicblueberry

**Comment by itisAliRH** [comment]
We have a PR for the admin panel that needs improvements and review: https://github.com/galaxyproject/galaxy/pull/16278

**Comment by neoformit** [comment]
I'm happy to brainstorm on UX/implementation

**Comment by itisAliRH** [comment]
Thank everyone for the discussion✌️

Suggestions that came up:
- [ ] Display an appropriate icon in the notification card and prioritize certain notifications, using the `source` field in the notification schema. For example. when the source is `admin`, the notification will be displayed with the correct icon and won't be deleted until the user has seen it.
- [ ] Group notifications from the same source in a period with no other sources notifications in between.
- [ ] Add a number indicator in the masthead icon.
- [ ] Show urgent and info/warning broadcasts at the same time when both groups are present.
- [ ] Use the carousel to view all news broadcasts.
- [ ] Dismiss unread broadcasts in one click
- [ ] Fix the CSS issue in the masthead tooltip.
- [ ] Replace the expire time icon in notifications with inline text.
- [ ] Use one button in the notification card (tick to read and trash to delete).
- [ ] Stick urgent broadcasts to the top of the list.
- [ ] Show broadcasts on the notifications page.
- [ ] Have a sticky header when scrolling.
- [ ] Change the preferences button to filled and add an arrow icon.
- [ ] Keep expired broadcasts in the admin panel to reference and reuse their content for later.
- [ ] Use the left border colour for unread notifications instead of the blue dot
- [ ] Use a hovercard for the broadcast container and apply a border colour that corresponds with the variant.
- [x] Remove icon blinking animation (galaxyproject/galaxy#16471)

**Comment by bgruening** [comment]
@itisAliRH if you move those items into a Galaxy issue we can close this here I think. I will clean up the title and the description a bit.

**Comment by itisAliRH** [comment]
@bgruening I created an issue and we can close this.

**Comment by bgruening** [comment]
Thanks
