### ISSUE TITLE
Admin discussion

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-au/elixir-biocommons-colab#8]
Random Admin discussion and identifying pain points and how we move the System WG forward.

**Comment by bgruening** [comment]
@hechth, @cat-bro, @hexylena, @pauldg

**Comment by cat-bro** [comment]
Ping @jlqfab

**Comment by cat-bro** [comment]
Would Friday 1:30pm be suitable?

**Comment by jlqfab** [comment]
Any time after lunch would suit me.

**Comment by hexylena** [comment]
I'll be in the vue meeting, so, I guess count me out

**Comment by cat-bro** [comment]
I spoke too soon - I'll be in the vue meeting too. Would 9am on Friday be OK?

**Comment by jlqfab** [comment]
9am is ok for me. I'm uunavailable from 10:30 - midday.

**Comment by pauldg** [comment]
9am works for me. I'll also be in the Vue workshop

**Comment by hechth** [comment]
So we do it before the second part of the vue meeting for like an hour? Then yeah, I think 9am would be good.

**Comment by pauldg** [comment]
@cat-bro let's rather organize this for today still please

**Comment by hexylena** [comment]
https://docs.google.com/document/d/1ByH8I2T8cPb00SmHhjMAypimRDMKxq4nKEXY8KawolQ/edit here is the existing usegalaxy membership document, please make your suggestions here! If they're not clear, please state what needs ot be clarified.

**Comment by hexylena** [comment]
Attendees: @hechth @pauldg @cat-bro @itisAliRH @bgruening @hexylena @shiltemann @jlqfab 
Missing: @natefoo

---

@natefoo we're discussing CVMFS here in Australia, would you be open to sharing administration of CVMFS (potentially with a prerequisite course of yours for those admins). @bgruening is quite worried about the bus factor.

@cat-bro is considering retiring the testing process on AU eventually, but the important aspect is that tools do have tests.

@bgruening discusses the tool yaml at EU will be reorganised into subdomains, and then those can be reused for the tool filters. @hexylena agrees this is great, makes it easier to setup subdomains. @cat-bro contributes that they're leaning to just listing all tools on subdomains since you're potentially missing out.

xref https://github.com/galaxyproject/usegalaxy-tools/, EU has motivation to re-start this, based on theirs 'subdomain' based yamls. @cat-bro agrees to install whatever we settle on, @natefoo would you be up for installing "whatever tools we all merge into this repo"? We try and build them up anew. We also try to force all of these new tools into singularity, and fallback to singularity with conda mounted. @bgruening promises EU has this fallback working and will add it to the GTN. We could in theory generate a skeleton tpv yaml from the list of these tools, and mark them all as `singularity: true`.

{TPV discussion that I missed}, but something like "annotate tools" . also annotate pulsar friendliness?

If you have non-working containers, please file a report and we should fix those containers. 

@natefoo has a list of 30% of tools on main that run in singularity, please provide this list to us.

@bgruening discusses
- https://github.com/usegalaxy-eu/mounts and wanting two headnodes.  Only problem is Interactive Tools, they explore moving that into postgres.
- mentions the complicated JWD setup, round robin on those.
- TUS is on a separate node for them

Systems WG
- does it exist
- do we want it to
- does it benefit any of us?
  - aus said it benefited them
- @bgruening wants a list of bugs every release. he thinks this would be most useful way for this group to work. (@hexylena agrees.)

Do we all switch to debian :sweat_smile:? @hexylena proposes it benefits the community, that we catch bugs we wouldn't've otherwise. Some VGCN discussion. Probably we don't?

@bgruening has switched pulsar to singularity, would rather hand-craft singularity containers. @bgruening will write the mulled command to hand-craft a container.

@cat-bro asks about walltime. US uses it, EU sets a 30 day walltime.

@bgruening is producing more ITs running desktop applications running in a VNC container. Remember that EU has a good template that they can share. @hexylena wants to run doom next week in Galaxy, @bgruening and her will work together on that :laughing:

**Comment by bgruening** [comment]
Thanks everyone for the great discussion!
